-- Tabel menu dinamis untuk SIMPOSYANDU (tambahan, tidak mengganggu tabel lama)
-- Jalankan sekali di database yang sama

CREATE TABLE IF NOT EXISTS `menus` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT 0,
  `title` varchar(100) NOT NULL,
  `url` varchar(255) DEFAULT '#',
  `icon` varchar(50) DEFAULT 'fas fa-circle',
  `order_num` int(11) DEFAULT 0,
  `is_header` tinyint(1) DEFAULT 0 COMMENT '1 = nav-header',
  `is_active` tinyint(1) DEFAULT 1,
  `role` varchar(50) DEFAULT NULL COMMENT 'null = semua role',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`),
  KEY `order_num` (`order_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed menu default (sesuai sidebar lama)
INSERT INTO `menus` (`parent_id`, `title`, `url`, `icon`, `order_num`, `is_header`, `is_active`) VALUES
(0, 'UTAMA', '#', '', 10, 1, 1),
(0, 'Beranda', 'dashboard.php', 'fas fa-home', 11, 0, 1),
(0, 'Statistik', 'modules/statistik/index.php', 'fas fa-chart-pie', 12, 0, 1),
(0, 'DATA WARGA', '#', '', 20, 1, 1),
(0, 'Kependudukan', '#', 'fas fa-users', 21, 0, 1),
(5, 'Penduduk', 'modules/penduduk/index.php', 'far fa-circle', 211, 0, 1),
(5, 'Keluarga', 'modules/keluarga/index.php', 'far fa-circle', 212, 0, 1),
(0, 'POSYANDU', '#', '', 30, 1, 1),
(0, 'Ibu Hamil', '#', 'fas fa-female', 31, 0, 1),
(9, 'Data Ibu Hamil', 'modules/ibu_hamil/index.php', 'far fa-circle', 311, 0, 1),
(9, 'Pemeriksaan', 'modules/pemeriksaan_ibu_hamil/index.php', 'far fa-circle', 312, 0, 1),
(0, 'Bayi', '#', 'fas fa-baby', 32, 0, 1),
(12, 'Data Bayi', 'modules/bayi/index.php', 'far fa-circle', 321, 0, 1),
(12, 'Pemeriksaan', 'modules/pemeriksaan_bayi/index.php', 'far fa-circle', 322, 0, 1),
(0, 'Balita', '#', 'fas fa-child', 33, 0, 1),
(15, 'Data Balita', 'modules/balita/index.php', 'far fa-circle', 331, 0, 1),
(15, 'Pemeriksaan', 'modules/pemeriksaan_balita/index.php', 'far fa-circle', 332, 0, 1),
(15, 'Imunisasi', 'modules/imunisasi/index.php', 'far fa-circle', 333, 0, 1),
(15, 'Vitamin', 'modules/vitamin/index.php', 'far fa-circle', 334, 0, 1),
(0, 'Remaja', '#', 'fas fa-user-graduate', 34, 0, 1),
(20, 'Data Remaja', 'modules/remaja/index.php', 'far fa-circle', 341, 0, 1),
(20, 'Pemeriksaan', 'modules/pemeriksaan_remaja/index.php', 'far fa-circle', 342, 0, 1),
(0, 'Lansia', '#', 'fas fa-user-friends', 35, 0, 1),
(23, 'Data Lansia', 'modules/lansia/index.php', 'far fa-circle', 351, 0, 1),
(23, 'Pemeriksaan', 'modules/pemeriksaan_lansia/index.php', 'far fa-circle', 352, 0, 1),
(0, 'KEGIATAN', '#', '', 40, 1, 1),
(0, 'Kegiatan Posyandu', 'modules/kegiatan_posyandu/index.php', 'fas fa-calendar-check', 41, 0, 1),
(0, 'Jadwal', 'modules/jadwal/index.php', 'fas fa-calendar-alt', 42, 0, 1),
(0, 'Kunjungan Rumah', 'modules/kunjungan_rumah/index.php', 'fas fa-home', 43, 0, 1),
(0, 'PENGATURAN', '#', '', 90, 1, 1),
(0, 'Kader', 'modules/kader/index.php', 'fas fa-user-nurse', 91, 0, 1),
(0, 'Pengaturan', 'modules/pengaturan/index.php', 'fas fa-cog', 92, 0, 1),
(0, 'Artikel', 'modules/artikel/index.php', 'fas fa-newspaper', 93, 0, 1);
